language: node_js
node_js:
  - "6"

before_install:
  - git config --global push.default matching
  - git config --global user.name "gasolin via Travis CI"
  - git config --global user.email "gasolin@gmail.com"
  - npm install hexo-cli -g
  - sed -i'' "s~https://github.com/gasolin/blog.git~https://${GH_TOKEN}@github.com/gasolin/blog.git~" _config.yml

install:
  - npm install

script:
  - hexo clean
  - hexo generate --quiet
  - cp feeds/posts/default.xml atom.xml
  - hexo deploy --quiet

branches:
  only:
    - master
cache:
  directories:
    - node_modules

