language: node_js
node_js:
  - "6.6.0"

before_install:
  - git config --global push.default matching
  - git config --global user.name "gasolin"
  - git config --global user.email "gasolin@gmail.com"
  - npm install hexo-cli -g
  - sed -i -- "s~https://github.com/gasolin/blog.git~https://$DEPLOY_REPO:x-oauth-basic@github.com/gasolin/blog.git~" _config.yml

install:
  - npm install

script:
  - hexo clean
  - hexo generate --deploy --debug

branches:
  only:
    - master
cache:
  directories:
    - node_modules

